Document: almanna
Title: Debian almanna Manual
Author: <insert document author here>
Abstract: This manual describes what almanna is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/almanna/almanna.sgml.gz

Format: postscript
Files: /usr/share/doc/almanna/almanna.ps.gz

Format: text
Files: /usr/share/doc/almanna/almanna.text.gz

Format: HTML
Index: /usr/share/doc/almanna/html/index.html
Files: /usr/share/doc/almanna/html/*.html
